# Darius-Florentin Neatu <neatudarius@gmail.com>

# Exemplu de Makefile pentru tema

# tag-uri obligatorii (nume + comportament identic)
# build    => compileaza toata tema
#             (ATENTIE! E important - NU compilati in tag-urile de run. Sesizati?)
# run-p$ID => ruleaza problema cu ID-ul specificat (1, 2, 3, 4)
# clean    => sterge toate fisierele generate

# restul este la alegerea studentului
# TODO

# nume necesar (build)
build:
	g++ -Wall crypto.cpp -o p1
	g++ -Wall stocks.cpp -o p2
	g++ -Wall valley.cpp -o p3
	g++ -Wall ridge.cpp -o p4

run-p1:      # nume necesar
	./p1
run-p2:      # nume necesar
	./p2
run-p3:      # nume necesar
	./p3
run-p4:      # nume necesar
	./p4
clean:		 # nume necesar
	rm -f p* *.o
